### ISSUE TITLE
SpunkForPCAP and Wireshark/Tshark version

### ISSUE THREAD

**Issue by ghost** [DanielSchwartz1/SplunkForPCAP#10]
Hello

I was testing the app on my windows install with Wireshark 4.x installed.. it didn't work (previously tested and it worked)
Removed Wireshark 4.x and installed Wireshark 2.x  It works.

Will the app being updated to support Wireshark 4.x

**Comment by DanielSchwartz1** [comment]
Hey @nspoor app will be updated in the next 2 weeks.

**Comment by DanielSchwartz1** [comment]
New Version 5.0.0 is online on the splunkbase.

**Comment by ghost** [comment]
Thankx for the update
