### ISSUE TITLE
PCAP Analyzer/WireShark Installation Guide

### ISSUE THREAD

**Issue by kevordista** [DanielSchwartz1/SplunkForPCAP#2]
Hi Daniel,

I am trying to used the PCAP Analyzer for Splunk
https://splunkbase.splunk.com/app/2748/
and also downloaded WireShark on my local stand-alone Splunk instance.

Just wanted to ask on some of the steps.
Step A: Make sure the ../SplunkForPCAP/bin/ folder has all administrative privileges to execute the batch and shell script
*I tried to check the ../SplunkForPCAP/bin/ folder >(Right click) > Properties > Security Tab
It has Read & execute, List folder contents and Read as Allow Permissions for Users
Do I need to add more or this will already suffice?
![image](https://user-images.githubusercontent.com/31677291/30091873-7a48524e-92ee-11e7-921c-ed6001ecb559.png)

Step B: Please specify the full path of the PCAP file location
* I had created a folder and use that path. Do I need to do something on the WireShark?
I tried to capture some packet data using WireShark and save it to the folder I had created and name it "http_test_wireshark.pcapng".  I am not quite sure if I am doing it right.
I had also configure the index "test_wireshark" and and sourcetype as pcap.
![image](https://user-images.githubusercontent.com/31677291/30091903-9e805d50-92ee-11e7-90a3-d59b2749342a.png)
![image](https://user-images.githubusercontent.com/31677291/30091922-b96fa008-92ee-11e7-8f0e-eec26de5d47a.png)

Unfortunately,  when I try to search, it seems like it captures events from the script and not using the configurations I made in Step B.
![image](https://user-images.githubusercontent.com/31677291/30092000-099b2f2a-92ef-11e7-8151-a3ff2b0d05b7.png)

**Comment by DanielSchwartz1** [comment]
Hi, sorry for being late. 
Step A is fine.
Step B file location is fine.
Step B file extension is wrong. You need to have .pcap file (not .pcapng). 
Put a .pcap file in your specified folder and the app will do the rest automatically.

Check also my post to get started: https://devops-online.com/pcap-analyzer-for-splunk-getting-started/.
