### ISSUE TITLE
Cannot get PCAP into the Tool

### ISSUE THREAD

**Issue by Christoway** [DanielSchwartz1/SplunkForPCAP#3]
Hello,
I followed all your instructions and couldn't get the PCAP File into your tool. How can I fix this?

**Comment by DanielSchwartz1** [comment]
Hi dustin2551,
what exactly is not working? Let me ask you some questions for it:
-You installed the app and have SPLUNK_HOME variable set properly?
-You set the folder (of your pcap files) via the web interface?
-is there an inputs.conf in your /SplunkForPCAP/local/ folder? Does it include your folder set via the web interface?
- Does your bin folder has exec grants?

Thanks

**Comment by christopher-combs** [comment]
Same issue. There is NO inputs.conf in the /SplunkForPCAP/local folder. in Fact, there is no local folder in the SplunkForPCAP directory.

**Comment by christopher-combs** [comment]
Additionally, my instance is running on Ubuntu server in a Virtual env. I set the $SPLUNK_HOME variable, but everything is loaded to $SPLUNK_HOME/splunk-7.1.1/opt/splunk/etc/apps/SplunkForPCAP/PCAPConverted/

Which I had to modify the converting scripts to reflect this.

Script FAILS on the line looking for the inputs.conf file as it is not there. (As mentioned in above comments) Thanks

**Comment by dbeniciorj** [comment]
Hello guys! Sorry to necromance this issue but I had the same problem. Here's how I fixed it. Hope it helps anyone who gets here.
1. adjusted SPLUNK_HOME dir default permissions to root:root
2. created a location for pcap new files scanning at /tmp/pcap with a=rwx permissions
3. created this input file for data ingestion $SPLUNK_HOME/etc/apps/SplunkForPCAP/local/inputs.conf :
[pcap://tmp_pcap]
index = default
path = /tmp/pcap
4. restarted splunk
