### ISSUE TITLE
Not sure if issue but ... Install Linux

### ISSUE THREAD

**Issue by collse** [DanielSchwartz1/SplunkForPCAP#4]
I had to do a few tweak to get this to work on Ubuntu.

1) wireshark didnt include tshark - needs manual install on ubuntu
2) /opt/splunk/etc/apps/SplunkForPCAP/bin/pcap2csv.sh caused errors

changed:
`if [[ "$TSHARK_V" =~ "$V2" ]]; then
	./$V11
elif [ "$TSHARK_V1" -le "10" ]; then
	./$V10
else
	./$V11`

to:
`if [[ "$TSHARK_V" =~ "$V2" ]]; then
	$V11
elif [ "$TSHARK_V1" -le "10" ]; then
	$V10
else
	$V11`

as otherwise it tries to call the script with ./ which returns a file/command not found 

not sure if the above is a general issue but I thought I mention it ...

feature request: allow pcap upload to /var/tmp from the interface ...

**Comment by DanielSchwartz1** [comment]
Hi Collse, 
thanks for the hint. I will check it. First time i hear about it.

Regarding your request. I am happy to hear new ideas. Can you specify what you mean?

**Comment by collse** [comment]
basically, a frontend that allows the pcap upload via your interface and that it will upload it to the specified directory, from where it will be read ... so I dont need to upload the pcaps via scp or so ..

**Comment by DanielSchwartz1** [comment]
Got it! Thanks! btw. I've uploaded new version 4.1.9 to splunkbase. As soon as it will be approved, I will close that issue. The new version will have your tweak implemented. Thanks again.

**Comment by collse** [comment]
Happy to help - keep up the good work!

**Comment by DanielSchwartz1** [comment]
Version 4.1.10 is available now.
